name: Introduction to Analysis of Ubiquitin
category: analysis
authors: ""
shortdesc: This course illustrates the application of a number of Python-based tools to the analysis of the results from a short (1 nanosecond) simulation of ubiquitin, investigating the question, how similar is the MD trajectory to the crystal and NMR structures?
longdesc: ""
